product/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from proje.views import *

app_name = "product"
urlpatterns = [
    path('<str:product>/<int:id>',
         product_buy_detail, name="product_detail"),
    path('buy/', buy_product, name="buy"),
    path('<int:id>/add-cart', add_cart),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proje/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from proje.views import home,buy_product

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('product/<str:product>/<int:id>', buy_product),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from  .views import * 


app_name = "user"

urlpatterns = [

    path('login/', loginUser, name='login'),

    path('logout/', logoutUser, name='logout'),

    path('signup/', register, name='signup'),

    path('profile/<str:username>', profile),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=50)

    def str(self):
        return "%s" % (self.name)


class Product(models.Model):
    name = models.CharField(max_length=50)
    count = models.IntegerField(verbose_name="count")
    price = models.FloatField(verbose_name="price")
    categories = models.CharField(max_length=400)
    image = models.FileField(verbose_name="image")
    company_name = models.ForeignKey(
        Company, verbose_name=("company"), on_delete=models.CASCADE)
    cart_count = models.IntegerField(null=True, blank=True, default=0)

    def _str_(self):
        return "%s" % (self.name)
    
    def categories_as_list(self):
        return self.categories.split(',')

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ['email', 'username', 'is_superuser']

product/views.py
from django.shortcuts import render

# Create your views here.

proje/views.py
from django.shortcuts import render, redirect, get_object_or_404
from product.models import Product
from django.contrib import messages
cart_item = 0
cart_list = list()

def home(request):
    return render(request, "home.html", {"cart_item": get_cart_item()})


def explore(request):
    products = Product.objects.all()
    args = {"products": products,
            "all_categories": get_all_categories(products), "cart_item": get_cart_item()
            }
    return render(request, "explore.html", args)


def get_all_categories(products):
    categories = list()
    i = 0
    for product in products:
        for i in range(len(product.categories.split(','))):
            categories.append(product.categories.split(',')[i])
    return list(dict.fromkeys(categories))


def your_cart(request):
    return render(request, "your_cart.html")


def product_buy_detail(request, product, id):
    product = get_object_or_404(Product, id=id)
    args = {"product": product}
    return render(request, "product_buy_detail.html", args)


def buy_product(request,product,id):
    obje=get_object_or_404(Product,id=id)
    obje.count-=1
    obje.save()
    return redirect('/explore')

def add_cart(request,id):
    cart_list = get_cart_list()
    product = get_object_or_404(Product, id=id)
    product.cart_count += 1
    product.save()
    set_cart_item(get_cart_item() + 1)
    if not product in cart_list:
        cart_list.append(product)
    messages.success(
        request, "Başarıyla '{}' Ürününü Sepete Eklediniz.".format(product.name))
    return redirect("/explore")

def get_cart_list():
    global cart_list
    return cart_list


def get_cart_item():
    global cart_item
    return cart_item


def set_cart_item(item):
    global cart_item
    cart_item = item
    return cart_item

    

    

    

user/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.core.mail import send_mail
from django.http import HttpResponse
from .forms import RegisterForm, LoginForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AdminPasswordChangeForm, PasswordChangeForm
from proje.views import get_cart_item, set_cart_item


def register(request):
    set_cart_item(0)
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username=username)
        newUser.set_password(password)

        newUser.save()
        login(request, newUser)

        return redirect("home")
    context = {
        "form": form
    }
    return render(request, "forms/register.html", context)


def loginUser(request):
    set_cart_item(0)
    form = LoginForm(request.POST or None)

    context = {
        "form": form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username=username, password=password)

        if user is None:
            return render(request, "forms/login.html", context)

        login(request, user)
        return redirect("home")
    return render(request, "forms/login.html", context)


def logoutUser(request):
    set_cart_item(0)
    logout(request)
    return redirect("home")


def profile(request, username):
    return render(request, "profile.html", {'cart_item': get_cart_item()})

templates/explore.html
{% extends 'layout.html' %}
{% block body %}
<div class="container">
    {% if messages %}

    {% for message in messages %}
    {% if message.tags == "info" %}
    <div class="alert alert-danger">{{ message }}</div>
    {% else %}
    <div class="alert alert-{{ message.tags }}">{{ message }} <a href="{% url 'your_cart'%}"
            class="alert-link">Buradan</a> sepetine
        gidebilirsin.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% endif %}
    {% endfor %}

    {% endif %}
</div>
<div class="container my-4">
    {% for category in all_categories %}
    <h1> {{category|upper}} </h1>
    <div class="row bg-secondary my-2 card-deck">
        {% for product in products %}
        {% if category in product.categories_as_list %}
        <div class="col">
            <div class="card ml-2 bg-secondary">
                <div class="card-header d-flex justify">
                    <a href="../product/{{product.name}}/{{product.id}}" class="lead productname">{{product.name}}
                        <small class="badge badge-success"
                            style="font-size: 0.75rem;">{{product.company_name}}</small></a>

                    <span class="lead text-dark"> &#36;{{product.price}}</span>
                </div>
                <div class="card-body">
                    {% for p_category in product.categories_as_list %}
                    <small class="badge badge-warning mb-2">{{p_category}}</small>
                    {% endfor %}
                    <p class="card-text text-warning">Some quick example text to build on the card title and make up the
                        bulk of
                        the
                        card's content.</p>
                </div>

                <div class="card-footer d-flex justify">

                    {% if product.count > 0 %}
                    <a href="../product/{{product.id}}/add-cart" class="btn btn-blue">Add
                        Cart</a>
                    {% else %}
                    <small class="badge badge-danger"> out of stock </small>
                    {% endif %}

                    <small class="text-warning"> {{product.count}} </small>
                </div>
            </div>
        </div>

        {% endif %}

        {% endfor %}
    </div>
    {% endfor %}

</div>
<style>
    .productname {
        color: #f6f6f6;
        font-size: 1.5rem;
    }

    .productname:hover,
    .productname:focus {
        color: #fbe3b9;
        text-decoration: none;
        transition: color 0.2s ease-in;
    }

    @media screen and (max-width: 600px) {

        .card-deck {
            display: block !important;
        }

        .card-header {
            display: grid !important;
        }
    }
</style>

{% endblock body %}

templates/forms/forms_layout.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta role="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="../../static/icons/LogoLight.png" type="image/x-icon">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>App</title>
</head>

<body>
    <div class="container-sm ">
        <div class="col-4 mx-auto bg-dark rounded">
            {% block form %}

            {% endblock %}
        </div>
    </div>

    <style>
        .container-sm {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            height: 100vh;
            background: #30475e;
        }
    </style>

    <script src="https://kit.fontawesome.com/802d737aeb.js"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

templates/forms/login.html
{% extends 'forms/forms_layout.html' %}
{% load crispy_forms_tags %}
{% block form %}


<form method="post" class="m-2" enctype="multipart/form-data">
    <h1 class="text-secondary">LOGIN</h1>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-md btn-outline-secondary mb-2">
        Sign In
    </button>
</form>
<div class="border-top pt-3 mb-3">
    <small class="text-muted">
        Need An account?
        <a href="{% url 'user:signup' %}" class="text-warning ml-2" style="text-decoration: none;"> SIGN UP </a>
    </small>

</div>


{% endblock %}

templates/forms/logout.html
{% extends 'forms/forms_layout.html' %}
{% load crispy_forms_tags %}
{% block form %}

<h2 class="m-2 text-secondary">You have been logged out.</h2>
<div class="pt-3 mb-3">
    <small class="text-muted">
        <a href="../login" class="text-warning nav-link"> LOG IN BACK </a>
    </small>
</div>

{% endblock %}

templates/forms/register.html
{% extends 'forms/forms_layout.html' %}
{% load crispy_forms_tags %}
{% block form %}
<h1 class="m-2 text-secondary">REGISTER</h1>
<form method="post" class="m-2" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type="submit" class="btn btn-outline-dark" style="  border-radius:10px;">JOIN US!</button>
</form>
<div class="border-top pt-3 mb-3">
    <small class="text-muted">
        Already Have An Account? <a href="{% url 'user:login' %}" class="text-warning ml-2"
            style="text-decoration: none;"> LOGIN </a>
    </small>
</div>

{% endblock %}

templates/home.html
{% extends "layout.html" %}
{% block body %}
<main role="main">

    <div class="container">

        <hr class="my-divider">

        <div class="row ">
            <div class="col-md-7">
                <h2 class="my-heading"> Your <span class="text-muted">safety</span>, our <span
                        class="text-muted">priority</span>.
                </h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis
                    euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus,
                    tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5 order-md-1 bg-light rounded flex justify-content-around">
                <div class="" style="align-items:center; display:block; margin-top:40px;">
                    <h1 style="font-size: 3rem;"> 10+ </h1>
                    <span style="font-size:1.2rem;"> years </span>
                </div>
                <div class="" style="align-items:center; display:block; margin-top:40px;">
                    <h1 style="font-size: 3rem;"> 4000+ </h1>
                    <span style="font-size:1.2rem;"> employees </span>
                </div>
            </div>
        </div>

        <hr class="my-divider">
        <div class="row ">
            <div class="col-md-7">
                <h2 class="my-heading"> Qualified <span class="text-warning">product</span>, maximum <span
                        class="text-warning">pleasure</span>.
                </h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis
                    euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus,
                    tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5 order-md-1 bg-light rounded flex justify-content-around">
                <div class="" style="align-items:center; display:block; margin-top:40px;">
                    <h1 style="font-size: 2.5rem;"> 212,230 </h1>
                    <span style="font-size:1.2rem;"> customers </span>
                </div>
                <div class="" style="align-items:center; display:block; margin-top:40px;">
                    <h1 style="font-size: 2.5rem;"> 1,468,134 </h1>
                    <span style="font-size:1.2rem;"> product sold </span>
                </div>
            </div>
        </div>

        <hr class="my-divider">

        <div class="row ">
            <div class="col-md-7">
                <h2 class="my-heading">We care about <span class="text-muted">partnership.</span>
                </h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis
                    euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus,
                    tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5 order-md-1 bg-light rounded flex justify-content-around">
                <div class="" style="align-items:center; display:block; margin-top:40px;">
                    <h1 style="font-size: 3rem;"> 20+ </h1>
                    <span style="font-size:1.2rem;"> association </span>
                </div>
                <div class="" style="align-items:center; display:block; margin-top:40px;">
                    <h1 style="font-size: 3rem;"> 0 </h1>
                    <span style="font-size:1.2rem;"> complaint </span>
                </div>
            </div>
        </div>

        <hr class="my-divider">

        <div class="contact-us col-6 mx-auto">
            <h1>Contact Us</h1>
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputEmail4">Email</label>
                        <input type="email" class="form-control" id="inputEmail4">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputname">Name</label>
                        <input type="text" class="form-control" id="inputname">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAddress">Your Message</label>
                    <textarea class="form-control" aria-label="With textarea"></textarea>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputCity">City</label>
                        <input type="text" class="form-control" id="inputCity">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="inputState">State</label>
                        <select id="inputState" class="form-control">
                            <option selected>Choose...</option>
                            <option>...</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputZip">Zip</label>
                        <input type="text" class="form-control" id="inputZip">
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck">
                        <label class="form-check-label" for="gridCheck">
                            Check me out
                        </label>
                    </div>
                </div>
                <button type="submit" class="btn btn-secondary">Send</button>
            </form>
        </div>

    </div>

</main>


<style>
    .marketing h2 {
        font-weight: 400;
    }


    .my-heading {
        font-weight: 300;
        line-height: 1;
        letter-spacing: -.05rem;
    }
</style>
{% endblock body %}

templates/includes/footer.html
<footer class="footer flex justify container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2020 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

templates/includes/navbar.html
<header class="header flex justify">

  <span class="lead text-success m-2">
      <svg class="bi bi-gift" width="1em" height="1em" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
              d="M2 6v8.5a.5.5 0 00.5.5h11a.5.5 0 00.5-.5V6h1v8.5a1.5 1.5 0 01-1.5 1.5h-11A1.5 1.5 0 011 14.5V6h1zm8-5a1.5 1.5 0 00-1.5 1.5c0 .098.033.16.12.227.103.081.272.15.49.2A3.44 3.44 0 009.96 3h.015L10 2.999l.025.002h.014A2.569 2.569 0 0010.293 3c.17-.006.387-.026.598-.073.217-.048.386-.118.49-.199.086-.066.119-.13.119-.227A1.5 1.5 0 0010 1zm0 3h-.006a3.535 3.535 0 01-.326 0 4.435 4.435 0 01-.777-.097c-.283-.063-.614-.175-.885-.385A1.255 1.255 0 017.5 2.5a2.5 2.5 0 015 0c0 .454-.217.793-.506 1.017-.27.21-.602.322-.885.385a4.434 4.434 0 01-1.104.099H10z"
              clip-rule="evenodd" />
          <path fill-rule="evenodd"
              d="M6 1a1.5 1.5 0 00-1.5 1.5c0 .098.033.16.12.227.103.081.272.15.49.2A3.44 3.44 0 005.96 3h.015L6 2.999l.025.002h.014l.053.001a3.869 3.869 0 00.799-.076c.217-.048.386-.118.49-.199.086-.066.119-.13.119-.227A1.5 1.5 0 006 1zm0 3h-.006a3.535 3.535 0 01-.326 0 4.435 4.435 0 01-.777-.097c-.283-.063-.614-.175-.885-.385A1.255 1.255 0 013.5 2.5a2.5 2.5 0 015 0c0 .454-.217.793-.506 1.017-.27.21-.602.322-.885.385a4.435 4.435 0 01-1.103.099H6zm1.5 12V6h1v10h-1z"
              clip-rule="evenodd" />
          <path fill-rule="evenodd"
              d="M15 4H1v1h14V4zM1 3a1 1 0 00-1 1v1a1 1 0 001 1h14a1 1 0 001-1V4a1 1 0 00-1-1H1z"
              clip-rule="evenodd" />
      </svg> CADEAU. </span>

  <div class="flex m-2 justify-content-between">
      <a class="link mr-2 mt-2 " href="/"><i class="fas fa-home mr-1"></i>Home</a>
      <a class="link ml-2 mt-2" href="/explore"><i class="fas fa-globe mr-1"></i>Explore</a>

      <div class="col-5">
          <input type="text" class="form-control" aria-label="Sizing example input"
              aria-describedby="inputGroup-sizing-sm" placeholder="Search something...">
      </div>
  </div>


  <div class="m-2">
      <a class="link" href="/your-cart"><small class="badge badge-secondary mr-1">{{cart_item}}</small><i
              class="fas fa-shopping-cart mr-1"></i>Your Cart</a>
      {% if user.is_authenticated %}
      <a href="/users/profile/{{user.username}}" class=" badge badge-warning ml-2">
          <svg class="bi bi-person-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 100-6 3 3 0 000 6z"
                  clip-rule="evenodd" />
          </svg> {{user.username}}</a>

      <a href="{% url 'user:logout' %}" class="link">
          <svg class="bi bi-box-arrow-in-right mr-1" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                  d="M8.146 11.354a.5.5 0 010-.708L10.793 8 8.146 5.354a.5.5 0 11.708-.708l3 3a.5.5 0 010 .708l-3 3a.5.5 0 01-.708 0z"
                  clip-rule="evenodd" />
              <path fill-rule="evenodd" d="M1 8a.5.5 0 01.5-.5h9a.5.5 0 010 1h-9A.5.5 0 011 8z" clip-rule="evenodd" />
              <path fill-rule="evenodd"
                  d="M13.5 14.5A1.5 1.5 0 0015 13V3a1.5 1.5 0 00-1.5-1.5h-8A1.5 1.5 0 004 3v1.5a.5.5 0 001 0V3a.5.5 0 01.5-.5h8a.5.5 0 01.5.5v10a.5.5 0 01-.5.5h-8A.5.5 0 015 13v-1.5a.5.5 0 00-1 0V13a1.5 1.5 0 001.5 1.5h8z"
                  clip-rule="evenodd" />
          </svg>logout
      </a>
      {% else %}

      <a class="link ml-1" href="{% url 'user:signup' %}"><i class="fas fa-sign-in-alt mr-1"></i>sign in</a>
      <a class="link ml-1" href="{% url 'user:login' %}"><i class="fas fa-plus mr-1"></i>login</a>
      {% endif %}


  </div>

  <style>
      @media screen and (max-width: 1080px) {
          .header {
              flex-direction: column;
              align-items: center;
              width: 100vw;
          }
      }
  </style>
</header>

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="main.css">
    <script src="https://kit.fontawesome.com/802d737aeb.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Tammudu+2&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body class="bg-blue">


   

  {% include 'includes/navbar.html' %}

{%block body%}

{%endblock body%}


  {% include 'includes/footer.html' %}

   
  <style>
    html,
    body {
        font-family: "Montserrat", sans-serif;
        background: #30475e;
    }

    body {
        width: 100%;
        color: #5a5a5a;

    }

    hr {
        margin: 4rem 0;
    }

    .wrapper {
        margin: 50px auto;
        min-height: calc(100vh - 200px);
        color: white;
        max-width: 80vw;
        width: 100%;
    }

    .bg-pink {
        background: #e7b2a5;
    }

    .bg-orange {
        background: #f1935c;
    }

    .bg-red {
        background: #ba6b57;
    }

    .bg-blue {
        background: #30475e;
    }

    .text-pink {
        color: #e7b2a5;
    }

    .text-orange {
        color: #f1935c;
    }

    .text-red {
        color: #ba6b57;
    }

    .text-blue {
        color: #30475e;
    }

    .m-5-a {
        margin: 80px auto;
    }

    .m-4-a {
        margin: 40px auto;
    }

    .m-3-a {
        margin: 20px auto;
    }

    .m-2-a {
        margin: 10px auto;
    }

    .m-1-a {
        margin: 5px auto;
    }



    .rounded {
        border-radius: 10px;
    }

    .flex {
        display: flex;
    }

    .justify {
        justify-content: space-between;
    }

    .product {
        max-width: 250px;
        max-height: 250px;
        margin: 10px;
    }



    .rounded-2 {
        border-radius: 20px;
    }


    img {
        width: 250px;
        height: 250px;
    }

    a {
        text-decoration: none;
    }

    .text-warning {
        color: #fbe3b9 !important;
    }

    .link:hover,
    .link:focus {
        color: #ba6b57;
        transition: color 0.1s ease-in;
        text-decoration: none;

    }

    .link {
        font-size: 0.75em;
        color: #fbe3b9;
        text-decoration: none;
    }

    .btn {
        border-radius: 5px;
        color: #30475e;
        font-size: 12px;
        padding: 5px;
    }

    .btn-orange {
        background: #f1935c;
        color: #30475e;
    }

    .btn-blue {
        background: #30475e;
        color: #f1935c;
    }

    .btn:focus,
    .btn:hover {
        transition: background-color 0.2s ease-in;
    }



    .header,
    .footer {
        max-width: 80vw;
        margin: 0 auto;
        width: 100%;
        padding: 10px;
    }

    .footer-wrapper {
        width: 100%;
        justify-content: space-around;
    }

    .product-group {
        flex-flow: row wrap;
        justify-content: space-around;
        padding-top: 0;
        margin: 0;
        list-style: none;
    }
</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>